#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc' in
 * file '/cygdrive/c/Users/kit/Documents/DS-5Workspace/user/soc.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'dma_enable_0', class 'dma_enable'
 * The macros are prefixed with 'DMA_ENABLE_0_'.
 * The prefix is the slave descriptor.
 */
#define DMA_ENABLE_0_COMPONENT_TYPE dma_enable
#define DMA_ENABLE_0_COMPONENT_NAME dma_enable_0
#define DMA_ENABLE_0_BASE 0x0
#define DMA_ENABLE_0_SPAN 8
#define DMA_ENABLE_0_END 0x7

/*
 * Macros for device 'Set_address_start_DMA_0', class 'Set_address_start_DMA'
 * The macros are prefixed with 'SET_ADDRESS_START_DMA_0_'.
 * The prefix is the slave descriptor.
 */
#define SET_ADDRESS_START_DMA_0_COMPONENT_TYPE Set_address_start_DMA
#define SET_ADDRESS_START_DMA_0_COMPONENT_NAME Set_address_start_DMA_0
#define SET_ADDRESS_START_DMA_0_BASE 0x8
#define SET_ADDRESS_START_DMA_0_SPAN 8
#define SET_ADDRESS_START_DMA_0_END 0xf


#endif /* _ALTERA_HPS_0_H_ */
