	soc u0 (
		.bus_clk_clk                     (<connected-to-bus_clk_clk>),                     //              bus_clk.clk
		.ctrl_reg_in_port                (<connected-to-ctrl_reg_in_port>),                //             ctrl_reg.in_port
		.ctrl_reg_out_port               (<connected-to-ctrl_reg_out_port>),               //                     .out_port
		.dma_adr_export                  (<connected-to-dma_adr_export>),                  //              dma_adr.export
		.dma_buf_size_export             (<connected-to-dma_buf_size_export>),             //         dma_buf_size.export
		.dma_status_export               (<connected-to-dma_status_export>),               //           dma_status.export
		.hps_io_hps_io_emac1_inst_TX_CLK (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>), //               hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0   (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),   //                     .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1   (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),   //                     .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2   (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),   //                     .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3   (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),   //                     .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0   (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),   //                     .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO   (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),   //                     .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC    (<connected-to-hps_io_hps_io_emac1_inst_MDC>),    //                     .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>), //                     .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>), //                     .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>), //                     .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1   (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),   //                     .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2   (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),   //                     .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3   (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),   //                     .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_sdio_inst_CMD     (<connected-to-hps_io_hps_io_sdio_inst_CMD>),     //                     .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0      (<connected-to-hps_io_hps_io_sdio_inst_D0>),      //                     .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1      (<connected-to-hps_io_hps_io_sdio_inst_D1>),      //                     .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK     (<connected-to-hps_io_hps_io_sdio_inst_CLK>),     //                     .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2      (<connected-to-hps_io_hps_io_sdio_inst_D2>),      //                     .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3      (<connected-to-hps_io_hps_io_sdio_inst_D3>),      //                     .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0      (<connected-to-hps_io_hps_io_usb1_inst_D0>),      //                     .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1      (<connected-to-hps_io_hps_io_usb1_inst_D1>),      //                     .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2      (<connected-to-hps_io_hps_io_usb1_inst_D2>),      //                     .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3      (<connected-to-hps_io_hps_io_usb1_inst_D3>),      //                     .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4      (<connected-to-hps_io_hps_io_usb1_inst_D4>),      //                     .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5      (<connected-to-hps_io_hps_io_usb1_inst_D5>),      //                     .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6      (<connected-to-hps_io_hps_io_usb1_inst_D6>),      //                     .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7      (<connected-to-hps_io_hps_io_usb1_inst_D7>),      //                     .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK     (<connected-to-hps_io_hps_io_usb1_inst_CLK>),     //                     .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP     (<connected-to-hps_io_hps_io_usb1_inst_STP>),     //                     .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR     (<connected-to-hps_io_hps_io_usb1_inst_DIR>),     //                     .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT     (<connected-to-hps_io_hps_io_usb1_inst_NXT>),     //                     .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim1_inst_CLK    (<connected-to-hps_io_hps_io_spim1_inst_CLK>),    //                     .hps_io_spim1_inst_CLK
		.hps_io_hps_io_spim1_inst_MOSI   (<connected-to-hps_io_hps_io_spim1_inst_MOSI>),   //                     .hps_io_spim1_inst_MOSI
		.hps_io_hps_io_spim1_inst_MISO   (<connected-to-hps_io_hps_io_spim1_inst_MISO>),   //                     .hps_io_spim1_inst_MISO
		.hps_io_hps_io_spim1_inst_SS0    (<connected-to-hps_io_hps_io_spim1_inst_SS0>),    //                     .hps_io_spim1_inst_SS0
		.hps_io_hps_io_uart0_inst_RX     (<connected-to-hps_io_hps_io_uart0_inst_RX>),     //                     .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX     (<connected-to-hps_io_hps_io_uart0_inst_TX>),     //                     .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA     (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),     //                     .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL     (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),     //                     .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA     (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),     //                     .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL     (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),     //                     .hps_io_i2c1_inst_SCL
		.hps_io_hps_io_gpio_inst_GPIO09  (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>),  //                     .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO35  (<connected-to-hps_io_hps_io_gpio_inst_GPIO35>),  //                     .hps_io_gpio_inst_GPIO35
		.hps_io_hps_io_gpio_inst_GPIO40  (<connected-to-hps_io_hps_io_gpio_inst_GPIO40>),  //                     .hps_io_gpio_inst_GPIO40
		.hps_io_hps_io_gpio_inst_GPIO53  (<connected-to-hps_io_hps_io_gpio_inst_GPIO53>),  //                     .hps_io_gpio_inst_GPIO53
		.hps_io_hps_io_gpio_inst_GPIO54  (<connected-to-hps_io_hps_io_gpio_inst_GPIO54>),  //                     .hps_io_gpio_inst_GPIO54
		.hps_io_hps_io_gpio_inst_GPIO61  (<connected-to-hps_io_hps_io_gpio_inst_GPIO61>),  //                     .hps_io_gpio_inst_GPIO61
		.i_pll_0_refclk_50mhz_clk        (<connected-to-i_pll_0_refclk_50mhz_clk>),        // i_pll_0_refclk_50mhz.clk
		.irq0_irq                        (<connected-to-irq0_irq>),                        //                 irq0.irq
		.led_clk_on_blue_export          (<connected-to-led_clk_on_blue_export>),          //      led_clk_on_blue.export
		.led_clk_on_green_export         (<connected-to-led_clk_on_green_export>),         //     led_clk_on_green.export
		.led_clk_on_red_export           (<connected-to-led_clk_on_red_export>),           //       led_clk_on_red.export
		.lines_delay_export              (<connected-to-lines_delay_export>),              //          lines_delay.export
		.memory_mem_a                    (<connected-to-memory_mem_a>),                    //               memory.mem_a
		.memory_mem_ba                   (<connected-to-memory_mem_ba>),                   //                     .mem_ba
		.memory_mem_ck                   (<connected-to-memory_mem_ck>),                   //                     .mem_ck
		.memory_mem_ck_n                 (<connected-to-memory_mem_ck_n>),                 //                     .mem_ck_n
		.memory_mem_cke                  (<connected-to-memory_mem_cke>),                  //                     .mem_cke
		.memory_mem_cs_n                 (<connected-to-memory_mem_cs_n>),                 //                     .mem_cs_n
		.memory_mem_ras_n                (<connected-to-memory_mem_ras_n>),                //                     .mem_ras_n
		.memory_mem_cas_n                (<connected-to-memory_mem_cas_n>),                //                     .mem_cas_n
		.memory_mem_we_n                 (<connected-to-memory_mem_we_n>),                 //                     .mem_we_n
		.memory_mem_reset_n              (<connected-to-memory_mem_reset_n>),              //                     .mem_reset_n
		.memory_mem_dq                   (<connected-to-memory_mem_dq>),                   //                     .mem_dq
		.memory_mem_dqs                  (<connected-to-memory_mem_dqs>),                  //                     .mem_dqs
		.memory_mem_dqs_n                (<connected-to-memory_mem_dqs_n>),                //                     .mem_dqs_n
		.memory_mem_odt                  (<connected-to-memory_mem_odt>),                  //                     .mem_odt
		.memory_mem_dm                   (<connected-to-memory_mem_dm>),                   //                     .mem_dm
		.memory_oct_rzqin                (<connected-to-memory_oct_rzqin>),                //                     .oct_rzqin
		.outclk_0_clk                    (<connected-to-outclk_0_clk>),                    //             outclk_0.clk
		.outclk_1_clk                    (<connected-to-outclk_1_clk>),                    //             outclk_1.clk
		.sdram0_address                  (<connected-to-sdram0_address>),                  //               sdram0.address
		.sdram0_burstcount               (<connected-to-sdram0_burstcount>),               //                     .burstcount
		.sdram0_waitrequest              (<connected-to-sdram0_waitrequest>),              //                     .waitrequest
		.sdram0_readdata                 (<connected-to-sdram0_readdata>),                 //                     .readdata
		.sdram0_readdatavalid            (<connected-to-sdram0_readdatavalid>),            //                     .readdatavalid
		.sdram0_read                     (<connected-to-sdram0_read>),                     //                     .read
		.sdram0_writedata                (<connected-to-sdram0_writedata>),                //                     .writedata
		.sdram0_byteenable               (<connected-to-sdram0_byteenable>),               //                     .byteenable
		.sdram0_write                    (<connected-to-sdram0_write>),                    //                     .write
		.status_reg_export               (<connected-to-status_reg_export>),               //           status_reg.export
		.timer_cnt_export                (<connected-to-timer_cnt_export>)                 //            timer_cnt.export
	);

